apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-f5si
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-f5si
    app.kubernetes.io/part-of: my-test-output
  name: pacman-f5si
  namespace: jephilli-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-f5si
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman-f5si
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:079cf227ab4e744ef777b9c4125039b2cadd7362a80b3b76f0bf3f0cdedbccb9
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
