apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-f5si
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-f5si
    app.kubernetes.io/part-of: my-test-output
  name: pacman-f5si
  namespace: jephilli-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pacman-f5si
    weight: 100
status: {}
